[package]
name = "font_helper"
version = "0.1.0"
authors = ["Chugunov Roman <Zebs-BMK@yandex.ru>"]
edition = "2018"

[dependencies]
libfonthelper = "0.2"
simple-server = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
